package protocol

import (
	"encoding/binary"
	"encoding/json"
	"fmt"
	"io"
)

// ControlMessageType distinguishes the different JSON control messages sent
// over the yamux control stream (stream 0, opened once at connection start).
// Using JSON here (rather than a hand-rolled binary format like
// StreamMetadata) is a deliberate choice: control messages are low-frequency
// and low-volume, so readability/extensibility wins over the few bytes saved
// by a binary encoding.
type ControlMessageType string

const (
	MsgHandshakeRequest  ControlMessageType = "handshake_request"
	MsgHandshakeResponse ControlMessageType = "handshake_response"
	MsgHeartbeat         ControlMessageType = "heartbeat"
	MsgHeartbeatAck      ControlMessageType = "heartbeat_ack"
	MsgRegisterRequest   ControlMessageType = "register_request"
	MsgRegisterResponse  ControlMessageType = "register_response"
	MsgRulesSnapshot     ControlMessageType = "rules_snapshot"
)

// HandshakeRequest is sent by the Client immediately after establishing the
// control TCP connection to the Server, before opening the yamux session.
//
// Unlike the original design (a single shared token + Client-dictated port
// list), the Client now authenticates with a per-Client identity
// (ClientID/ClientSecret, issued once via the registration flow below) and
// does NOT request any ports -- which ports are forwarded for this Client
// is entirely decided by the Server/panel operator and pushed to the
// Client via RulesSnapshot after a successful handshake. This is what
// makes "open a port only when the admin enables it in the panel" possible:
// the Client has no authority to claim arbitrary remote ports.
type HandshakeRequest struct {
	Type            ControlMessageType `json:"type"`
	ProtocolVersion uint8              `json:"protocol_version"`
	ClientID        string             `json:"client_id"`
	ClientSecret    string             `json:"client_secret"`
	ClientVersion   string             `json:"client_version"`
}

// PortBinding describes one port the Server listens on (TCP, UDP, or both)
// and forwards to a Client. Retained for wire-compatibility with
// RulesSnapshot's per-rule transport flags.
type PortBinding struct {
	Port uint16 `json:"port"`
	TCP  bool   `json:"tcp"`
	UDP  bool   `json:"udp"`
}

// HandshakeResponse is the Server's reply. It no longer carries an
// AcceptedPorts list -- the Client learns its active rule set exclusively
// via the RulesSnapshot message the Server sends immediately afterward.
type HandshakeResponse struct {
	Type            ControlMessageType `json:"type"`
	OK              bool               `json:"ok"`
	Error           string             `json:"error,omitempty"`
	ProtocolVersion uint8              `json:"protocol_version"`
	ServerVersion   string             `json:"server_version"`
}

// RegisterRequest is sent by a Client that only has a one-time registration
// token (freshly generated by the panel's "add client" flow, embedded in
// the one-line install command) and does not yet have a persistent
// ClientID/ClientSecret pair. This happens exactly once per Client
// lifetime (first boot after install); the Client persists the returned
// credentials to local disk and uses HandshakeRequest for every connection
// after that.
type RegisterRequest struct {
	Type            ControlMessageType `json:"type"`
	ProtocolVersion uint8              `json:"protocol_version"`
	RegisterToken   string             `json:"register_token"`
	ClientVersion   string             `json:"client_version"`
	// Hostname is a best-effort display hint for the panel (the operator
	// can rename the Client later); purely informational, never trusted
	// for authorization decisions.
	Hostname string `json:"hostname"`
}

// RegisterResponse carries the newly minted permanent credentials. The
// register token is single-use: the Server marks it consumed as soon as it
// hands out a ClientID/ClientSecret pair, so replaying a captured
// registration command after first use does not grant a second identity.
type RegisterResponse struct {
	Type         ControlMessageType `json:"type"`
	OK           bool               `json:"ok"`
	Error        string             `json:"error,omitempty"`
	ClientID     string             `json:"client_id"`
	ClientSecret string             `json:"client_secret"`
}

// RuleProtocol identifies which transport a forwarding rule applies to.
type RuleProtocol string

const (
	RuleProtocolTCP RuleProtocol = "tcp"
	RuleProtocolUDP RuleProtocol = "udp"
	// RuleProtocolBoth is a dual-stack rule: the Server opens both a TCP and
	// a UDP listener on the same public port. Individual streams still carry
	// TransportTCP or TransportUDP in their metadata, so the Client needs no
	// special handling for it.
	RuleProtocolBoth RuleProtocol = "tcp+udp"
)

// Rule is one forwarding rule as pushed from Server to Client. This is the
// authoritative, Server-owned description of "what should this Client be
// doing right now" -- the Client has no local rule configuration of its
// own anymore (see docs/01-architecture.md and docs/03-product-design.md).
type Rule struct {
	ID               int64        `json:"id"`
	Name             string       `json:"name"`
	Protocol         RuleProtocol `json:"protocol"`
	LocalIP          string       `json:"local_ip"`
	LocalPort        uint16       `json:"local_port"`
	RemotePort       uint16       `json:"remote_port"`
	PreserveSourceIP bool         `json:"preserve_source_ip"`
}

// RulesSnapshot is pushed by the Server to a connected Client: once right
// after a successful handshake, and again every time the panel operator
// adds/edits/enables/disables/removes a rule for this Client while it
// stays connected. It is always a full snapshot (not a delta) of every
// currently-ENABLED rule for this Client -- the Client's rulesync
// reconciler diffs it against its own currently-running forwarders and
// starts/stops exactly what changed. Disabled rules are simply absent from
// this list; the Client does not need to know they exist at all.
type RulesSnapshot struct {
	Type  ControlMessageType `json:"type"`
	Rules []Rule             `json:"rules"`
}

// HeartbeatMessage is sent periodically by the Client to let the Server know
// it's still alive. The Server resets its per-client timeout timer on
// receipt. See docs/02 for the companion client-side watchdog design (which
// is about local deployment safety, not this wire-level heartbeat).
type HeartbeatMessage struct {
	Type         ControlMessageType `json:"type"`
	SequenceNum  uint64             `json:"seq"`
	UnixTimeNano int64              `json:"unix_time_nano"`
}

type HeartbeatAck struct {
	Type        ControlMessageType `json:"type"`
	SequenceNum uint64             `json:"seq"`
}

// WriteJSONMessage writes a length-prefixed JSON message to w. All control
// messages on the control stream use this framing: a 4-byte big-endian
// length prefix followed by that many bytes of JSON. This avoids needing a
// JSON stream decoder that could accidentally read ahead into stream data
// (which matters once the control stream is multiplexed with yamux, although
// in the current design control messages live on their own dedicated
// stream 0, so this is mostly defense in depth).
func WriteJSONMessage(w io.Writer, v interface{}) error {
	data, err := json.Marshal(v)
	if err != nil {
		return fmt.Errorf("protocol: marshal control message: %w", err)
	}
	if len(data) > 1<<20 {
		return fmt.Errorf("protocol: control message too large (%d bytes)", len(data))
	}
	lenBuf := make([]byte, 4)
	binary.BigEndian.PutUint32(lenBuf, uint32(len(data)))
	if _, err := w.Write(lenBuf); err != nil {
		return fmt.Errorf("protocol: write length prefix: %w", err)
	}
	if _, err := w.Write(data); err != nil {
		return fmt.Errorf("protocol: write payload: %w", err)
	}
	return nil
}

// ReadJSONMessage reads one length-prefixed JSON message from r and unmarshals
// it into v.
func ReadJSONMessage(r io.Reader, v interface{}) error {
	lenBuf := make([]byte, 4)
	if _, err := io.ReadFull(r, lenBuf); err != nil {
		return fmt.Errorf("protocol: read length prefix: %w", err)
	}
	n := binary.BigEndian.Uint32(lenBuf)
	if n > 1<<20 {
		return fmt.Errorf("protocol: control message too large (%d bytes)", n)
	}
	data := make([]byte, n)
	if _, err := io.ReadFull(r, data); err != nil {
		return fmt.Errorf("protocol: read payload: %w", err)
	}
	if err := json.Unmarshal(data, v); err != nil {
		return fmt.Errorf("protocol: unmarshal control message: %w", err)
	}
	return nil
}

// PeekMessageType reads just enough of a raw JSON message to determine its
// Type field, without consuming it from the underlying reader permanently.
// This is a convenience helper for a generic dispatch loop; most call sites
// know statically which message type to expect next and can call
// ReadJSONMessage directly instead.
type typeOnly struct {
	Type ControlMessageType `json:"type"`
}

func PeekType(data []byte) (ControlMessageType, error) {
	var t typeOnly
	if err := json.Unmarshal(data, &t); err != nil {
		return "", err
	}
	return t.Type, nil
}
